### ISSUE TITLE
not able to subscribe private channel

### ISSUE THREAD

**Issue by ankit22451847** [pusher/pusher-websocket-java#128] opened 2016-11-14 11:45 UTC
I think that there is problem in:

 if(channelName.matches(disallowedPattern)) {
                    throw new IllegalArgumentException("Channel name " + channelName + " is invalid. Private channel names must start with \"private-\" and presence channel names must start with \"presence-\"");
                }

it throw exception

**Comment by zmarkan** [comment] 2017-01-05 15:37
I think this is a duplicate of https://github.com/pusher/pusher-websocket-java/issues/127

**Closed by zmarkan** 2017-01-05 15:37 UTC
