### ISSUE TITLE
NullPointerException when authorizing private channel

### ISSUE THREAD

**Issue by lttlang** [pusher/pusher-websocket-java#357] opened 2023-04-27 19:58 UTC
### What is the issue?
We recently updated the pusher lib from 2.0.2 to 2.4.4 and began experiencing crashes in production. Our android app retrieves its channel authorization token from our backend servers and this request can potentially (and does occasionally) fail. In this case, we return a null authorization token in our ChannelAuthorizer implementation.

It seems that in [this](https://github.com/pusher/pusher-websocket-java/pull/278) commit there was an inadvertent behavior change with the situation above. The deserialization of the authResponse [here](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java#L83) can result in a null object and we're no longer catching all exceptions [here](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java#L94) . In the 2.0.2 [version](https://github.com/pusher/pusher-websocket-java/blob/v2.0.2/src/main/java/com/pusher/client/channel/impl/PrivateChannelImpl.java#L112) of the lib, a NullPointException is caught and an AuthorizationFailureException is thrown .  

### Is it a crash report? Submit stack traces or anything that you think would help
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.pusher.client.channel.impl.message.AuthResponse.getChannelData()' on a null object reference
       at com.pusher.client.channel.impl.PrivateChannelImpl.authorize(PrivateChannelImpl.java:84)
       at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:101)
       at com.pusher.client.channel.impl.ChannelManager.lambda$sendOrQueueSubscribeMessage$0(ChannelManager.java:134)
       at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:140)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

### Any improvements you suggest

...

---- 
Thank you!

CC @pusher/mobile

**Comment by gabrielginter** [comment] 2023-07-07 04:30
I'm experiencing the same crash in Production, through the flutter plugin. @lttlang did you manage a workaround for this?

**Comment by lttlang** [comment] 2023-07-07 13:04
We haven't released a workaround for our app to production, and are holding off upgrading the lib.

You could pass an empty JSON string ("{}"), rather than a null authorization token. I think that would at least workaround the initial null pointer exception but I'm not sure if that would cause other issues.

**Comment by gabrielginter** [comment] 2023-07-07 17:42
Thanks for your message, I was actually throwing an Exception which had the same result, I've implemented some connection checks and a couple retries to prevent crashes, for the time being it seems to work but crashes still happen if connection is not restored after a certain period of time.

BTW: this issue is also reproducible on iOS

@benw-pusher would it be possible to prioritise this fix in the following update?

**Comment by benjamin-tang-pusher** [comment] 2023-08-22 20:13
I'm trying to reproduce this issue in a Java client (not flutter, which now has its own workaround), and when I get our auth endpoint return null, its correctly caught: `Authentication failure due to [Unable to parse response from Authorizer: ],`

You mentioned a null authorization token, could you clarify this: whats the string returned by your auth endpoint?

In my experience with other customers reporting this issue, there is definitely some invalid auth responses that aren't handled by the library well.

**Comment by benw-pusher** [comment] 2024-03-26 15:14
We haven't had a response here so closing. Please get in touch at https://messagebird.com/support-center/Pusher-request-new if you need further suppor

**Closed** 2024-03-26 15:15 UTC

**Comment by rajatsharma16** [comment] 2025-05-31 16:32
Did this get solved for you @lttlang @benw-pusher The root issue is.

`final AuthResponse authResponse = GSON.fromJson(getAuthorizationResponse(), AuthResponse.class);` // getAuthorizationResponse returns null
 `channelData = authResponse.getChannelData();`// NPE
