### ISSUE TITLE
Pusher Gives error when tried to subscribe Presence Channel

### ISSUE THREAD

**Issue by RameshBhupathi** [pusher/pusher-websocket-java#132] opened 2016-12-19 12:11 UTC
Error :onAuthenticationFailure: Failure Unable to parse response from Authorizer: null

Using Php server side library--Pusher-Cl

>  "{"auth":"6f3dd2fb8dc80bafba32:8c65c7816224b35dbc4fe1f753b47482d0ff0102818e2bff78ba3d80c4286bee","channel_data":"{\"user_id\":\"5\",\"user_info\":{\"name\":\"Android Test\"}}"}"

**Comment by zmarkan** [comment] 2017-01-05 15:58
Seems to me like an issue with the Authorizer implementation on the server-side. Please check your response is similar to the one specified here: https://pusher.com/docs/authenticating_users - namely, it has to be JSON but encoded as a String.

**Comment by RameshBhupathi** [comment] 2017-09-16 07:11
@zmarkan My reposne is
{
"auth":"278d425bdf160c739803:a99e78e7cd40dcd0d4ae06be0a5395b6cd3c085764229fd40b39ce92c39af33e"
}

**Comment by RameshBhupathi** [comment] 2017-09-16 13:34
@zmarkan i figured out the issue, **authorize** method is returns the null vlaue with put waiting for the response, for now doing synchronise api call to make it work ...
 so please suggest me best way, using Volley for API calls.

**Comment by zmarkan** [comment] 2017-09-18 09:05
Hi @RameshBhupathi,
If you're subscribing to a Presence channel you're missing the `channel_data` part of the response. It is a required so I assume that's what causing the null error. 

Additionally - the `channel_data` value has to be a valid JSON _encoded as a string_.

Sample response:
```
{
"auth":"WHATEVER_THE_AUTORIZER_GIVES_YOU",
"channel_data":"{\"user_id\":\"zmarkan\",\"some_other_param\":12345\}"
}

Please note the escaped values for `{`, `}`, and `"`. They are prefixed by a `\`. This is also required.

Let me know how it goes.

**Comment by RameshBhupathi** [comment] 2017-09-18 14:17
@zmarkan subscribing to **PrivateChannel** figured out the issue, Actually Problem is  **authorize** method is returns the null value with out waiting for the API Call which done inside the method, so used to get this null response(Because sending the null to authorize method)

for now doing synchronise api(blocking the code untill i get the api repsonse) call to make it work ...

so please suggest me best way to do this with out blocking ,for api calls i used Volley.

**Comment by zmarkan** [comment] 2017-09-18 14:45
The `Authorizer.authorize` method is blocking by design. The Pusher SDK will execute it on a background thread and you shouldn't have to do anything - just make a blocking call.

I'm not sure what your implementation is, but here's one way to do it: https://stackoverflow.com/a/17035421/643516

**Comment by kn100** [comment] 2018-05-23 16:20
Closing due to age

**Closed by kn100** 2018-05-23 16:20 UTC
