### ISSUE TITLE
Pusher object says it is connected, subscribed, and events are bound, but no event callbacks are fired if the android device sleeps.

### ISSUE THREAD

**Issue by DeanSolecki** [pusher/pusher-websocket-java#154] opened 2017-09-19 00:30 UTC
### What is the issue?

The pusher object connects, subscribes, and binds correctly.  Events arrive as expected.

In some circumstances which I can't determine the pusher object says that it is connected, subscribed, and bound, but events are no longer received (log in "onEvent" never prints, but all methods are getting called up to that point.)  It ~seems~ like it has something to do with the app being backgrounded, but I'm not entirely sure, since it doesn't always happen.  Is this a known issue?

CC @pusher/mobile

**Comment by zmarkan** [comment] 2017-09-19 07:33
Hi, 
once the app is backgrounded the Android OS could kill it at any time - to do GC or battery optimisations due to network usage. All bets are off, unfortunately.

I'd recommend you unbind from events when that happens - maybe use a push notification to get events to your users in the background? https://pusher.com/docs/push_notifications/android

**Comment by DeanSolecki** [comment] 2017-09-20 18:39
Hi zmarkan,

The situation I'm dealing with is that I actually don't *want* pusher to be active in the background, but the pusher object's methods act like pseudo Class methods; as in, I call disconnect on a pusher object in activity A and create a new pusher object in activity B, but the previous pusher object's disconnect call has not completed, so it either believes that it is still subscribed to a channel or it fails to reconnect.  Because I have lost access to that callback I no longer have the ability to act on "disconnecting"/"disconnected" states of the pusher object.

To be less cryptic, I what I'm trying to achieve is this:

Activity A binds to events on onStart, unbinds on onPause.
Activity B binds to events on onStart, unbinds on onPause.

With the caveat being that I want the tcp socket closed when the app is not foreground.

What is the correct way to go about this?

**Comment by zmarkan** [comment] 2017-09-21 06:29
Make sure to only have a single `Pusher` object in your app that is shared between all activities, don't instantiate a new Pusher per each activity.

**Comment by DeanSolecki** [comment] 2017-09-22 21:09
Thanks for the help.

When I try to unbind and then rebind I seem to end up with multiple listeners all firing on events.  Is there some way to unbind all events?  Or else is there some way to replace a binding other than simply calling unbind("event", listener)?  I have one pusher object, one channel (unless it becomes null as a result of Android lifecycle, which I check for) and 4 possible bindings.  I'm not sure what to do at this point.

**Comment by DeanSolecki** [comment] 2017-09-22 21:36
Another thing I'm not understanding is what happens to a disconnected pusher object when the app is backgrounded?  Is there any way to be sure that the pusher object can still be used?  I over and over again am running into a situation where pusher says it is connected, subscribed, and bound to events, but no events arrive.  If I destroy the pusher object (or release it to garbage collection) the new pusher object will occasionally report that the channel is already subscribed, even if I have explicitly disconnected.

If I can't destroy, nor trust, a single pusher object, what is a workaround?

**Comment by zmarkan** [comment] 2017-09-26 07:22
What you're describing seems to be the right way to do it. I'll investigate this today, and try to reproduce your issue. This definitely shouldn't have happened - after you unbind & unsubscribe that should be it.

**Comment by zmarkan** [comment] 2017-10-03 09:14
I understand this conversation has moved to the support channel. Closing this ticket now.

**Closed by zmarkan** 2017-10-03 09:14 UTC
