### ISSUE TITLE
Attempted to create an connection state update where both previous and current state are: CONNECTED

### ISSUE THREAD

**Issue by maxoumime** [pusher/pusher-websocket-java#145] opened 2017-05-04 22:18 UTC
Hi there,

I am having some issues crashes on my Android app where I would get this exception: 
**Attempted to create an connection state update where both previous and current state are: CONNECTED.** I don't find any class from my app in the stack trace. Pusher is a singleton instance in the code.

I see it happening on Android major versions 5 (Lollipop), 6 (Marshmallow) and 7 (Nougat), as we don't have a lot of 4.* devices, it might also crash on those devices.

This is what I log from devices which crashed:
```
18:48:30:534 | D/CrashlyticsCore Pusher connection changed : CONNECTED to RECONNECTING
18:48:31:540 | D/CrashlyticsCore Pusher connection changed : RECONNECTING to CONNECTING
18:55:27:064 | D/CrashlyticsCore Pusher connection changed : CONNECTING to CONNECTED
18:55:29:067 | D/CrashlyticsCore Pusher connection changed : CONNECTED to RECONNECTING
19:00:23:766 | D/CrashlyticsCore Pusher connection changed : RECONNECTING to CONNECTING
19:00:30:080 | D/CrashlyticsCore Pusher connection changed : CONNECTING to RECONNECTING
19:00:30:084 | D/CrashlyticsCore Pusher connection error : An exception was thrown by the websocket null
```

Sometimes only one of this lines makes the app crash, and sometimes there are hundreds of reconnections and a few `exception was thrown by the websocket null`.

Any insights about this? Thanks!

This is the stack trace:

```
#0. Crashed: pusher-java-client eventQueue: 0 0 0x0000000000000000
       at com.pusher.client.connection.ConnectionStateChange.(ConnectionStateChange.java:21)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:152)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleConnectionMessage(WebSocketConnection.java:194)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleInternalEvent(WebSocketConnection.java:180)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:171)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$000(WebSocketConnection.java:28)
       at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:255)
       at com.pusher.client.util.Factory$1.run(Factory.java:103)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

--

Fatal Exception: java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: CONNECTED
       at com.pusher.client.connection.ConnectionStateChange.(ConnectionStateChange.java:21)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:152)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleConnectionMessage(WebSocketConnection.java:194)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleInternalEvent(WebSocketConnection.java:180)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:171)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$000(WebSocketConnection.java:28)
       at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:255)
       at com.pusher.client.util.Factory$1.run(Factory.java:103)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

#0. Crashed: pusher-java-client eventQueue: 0 0 0x0000000000000000
       at com.pusher.client.connection.ConnectionStateChange.(ConnectionStateChange.java:21)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:152)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleConnectionMessage(WebSocketConnection.java:194)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleInternalEvent(WebSocketConnection.java:180)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:171)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$000(WebSocketConnection.java:28)
       at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:255)
       at com.pusher.client.util.Factory$1.run(Factory.java:103)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

```

**Comment by zmarkan** [comment] 2017-05-05 05:38
Hello!

What version of the `pusher-java-client` library are you using? Is it `1.4.0`? 

There should be a fix for that issue in `1.5.0`. It's available in Maven Central but I haven't updated the docs yet.

**Comment by maxoumime** [comment] 2017-05-05 16:16
Oh ok, I updated to 1.5.0 recently so I didn't have enough data to see if it made a change. Will keep you posted then

**Comment by zmarkan** [comment] 2017-05-05 16:17
Thanks! 👍🏻

**Comment by sirajsolutelabs** [comment] 2017-06-13 04:36
Hello,

This crash issue is recorded in my app also. @zmarkan Can you please let us know what should be the cause of this issue? Can we be aware of some codes causing this issue?

Thanks

**Comment by zmarkan** [comment] 2017-06-13 05:38
What version of the library are you using? This issue was fixed in `v1.5.0`

**Comment by sirajsolutelabs** [comment] 2017-06-13 05:40
I am using 1.4.0 as the document is not updated. On changing the version, I am no more getting the issue. But still I will test with other data. Also Can you please explain this issue? It will be a great help

**Comment by zmarkan** [comment] 2017-06-13 05:47
Ok, I'll update the docs. `v1.5.0` is definitely the latest version that has this issue fixed.

It uses naive waits to reconnect - sometimes it come out of the wait after it's been connected. The fix ignores that state and permits it to happen.

**Closed by zmarkan** 2017-06-13 05:47 UTC
