### ISSUE TITLE
Throwing OutOfMemoryError

### ISSUE THREAD

**Issue by traic** [pusher/pusher-websocket-java#95] opened 2016-02-02 16:29 UTC
I just included the latest version 1.0.2 pusher client library into my project (also testing older versions), and they seem to be causing OOM errors in my app. The application freezes up on app start and just leaks out on GenyMotion. Any clues?

**Comment by jpatel531** [comment] 2016-03-23 22:30
Hi there, do you have some reconnection logic that calls connect immediately upon disconnecting? Also could you share a stacktrace?

**Comment by SanjayPrajapati-solutelabs** [comment] 2017-06-05 09:42
Have you found any solution?

I am using pusher version 1.0.4 

and below is my crash log
`Fatal Exception: java.lang.RuntimeException: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
       at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
       at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
       at com.loopj.android.http.AsyncHttpClient.sendRequest(AsyncHttpClient.java:1508)
       at com.loopj.android.http.AsyncHttpClient.post(AsyncHttpClient.java:1169)
       at com.pusher.android.notifications.interests.SubscriptionManager.sendSubscription(SubscriptionManager.java:70)
       at com.pusher.android.notifications.interests.SubscriptionManager.sendSubscriptions(SubscriptionManager.java:48)
       at com.pusher.android.notifications.PushNotificationRegistration.onSuccessfulRegistration(PushNotificationRegistration.java:186)
       at com.pusher.android.notifications.tokens.RegistrationListenerStack.onSuccessfulRegistration(RegistrationListenerStack.java:31)
       at com.pusher.android.notifications.tokens.TokenUpdateHandler.onSuccess(TokenUpdateHandler.java:34)
       at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
       at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by zmarkan** [comment] 2017-06-05 11:09
Hi there!

It appears you are referring to our [Push Notifications library - pusher-websocket-android](https://github.com/pusher/pusher-websocket-android). 

I also believe the original question was related to the `pusher-java-Java client - that one contains just the Pub/Sub over WebSocket). It mentioned a very old version, so I presume the original issue has been fixed.

Lastly, the version `1.0.4` you're referring to doesn't exist. Maybe you mean `1.4.0`? But again, that's only the `pusher-java-client`and not the Android push notification library - `pusher-websocket-android`.

I will close this issue for now. Please double check and reopen, either in the relevant repository, or open a support ticket.
Thanks

**Closed by zmarkan** 2017-06-05 11:09 UTC
